title: Brydon's Blog
email: brydon.leonard@gmail.com
description: >- 
  Brydon's Blog. The blog belonging to Brydon. I write about whatever I find interesting.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: BrydonLeonard 

# Build settings
theme: minima

minima:
  date_format: "%Y-%m-%d"

kramdown:
  math_engine: mathjax

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
